### ISSUE TITLE
Use a heuristic to auto-apply dbx updates

### ISSUE THREAD

**Issue by hughsie** [rhinstaller/dbxtool#7]
At the moment dbxtool.service unconditionally applies dbx updates in `/usr/share/dbxtool` which is suboptimal when people have installed versions of shim/grub which will not boot with the updated dbx table.

My proposal would be something like this:

 * Ship the new updated dbx update in this repo, and install it to `/usr/share/dbxtool` like the other update.
 * Add a `--check-certs` argument to the `dbxtool.service`
 * Add a `check_certs` argument to `dbxtool` CLI, which checks the certificate timestamp of the installed `shim` (and `grub`?) on the ESP
 * Add some metadata to the installed files (perhaps something like `/usr/share/dbxtool/xmls/DBXUpdate-2016-08-09-13-16-00.xml`) which specifies the minimum certificate timestamp required to auto-apply the dbx update -- XML/JSON/TXT format irrelevant. I don't think a "_checksum allow-list_" scales but it's another simpler idea.

Some comments:

 * If the `check-shim` heuristic fails, the user can apply the dbx update manually, just by missing out the `--check-shim` argument or maybe a `--force` argument instead
 * We don't really care about non-FAT32 ESPs or multiple-ESPs
 * We need to log a warning in the journal if the update service fails due to the ESP check somewhere the admin will see
 * We'd need to grow a OpenSLL dep in dbxtool to read the certificate signature timestamps I think
 * We need to fail the `--check-certs` argument if running on a LiveCD media as the ESP won't be the system ESP.

**Comment by vathpela** [comment]
Okay, a couple of minor things I see:
- new dbx files will be broken down by EFI arch, so we have to decide how to handle that.  My initial thought is we probably want to just stick it in the filename before or after the date code, and carry them all no matter what build target (they're useful for reference in any case)
- probably ought to make the second stage loader (i.e. grubx64.efi) compile-time configured and check it against MokListRT (which on some systems is now MokListRT MokListRT1..MokListRTN due to the insane space limits)
- even with all that I'm not sure I see the point of a metadata file.  dbx updates come in atomic signed blobs. What's wrong with just having a "current" symlink and having the admin move it when they choose to apply a newer one than the recommended option?
- Do you think something analogous to e7bb68cb53bd08c34b7fe6f1ad6e15154f749eb9 is enough for the LiveCD check?
 - I am thinking we might want a --force for both checking and applying that says "I know this is a live image, do it anyway", so users can use live images to update their fleets if need be.

**Comment by hughsie** [comment]
> new dbx files will be broken down by EFI arch, so we have to decide how to handle that

I guessed per-EFI-arch subdirectories....

> stick it in the filename before or after the date code

I think encoding everything into the filename isn't going to work when we add even more metadata. I think at some point (now?) we need a catalog with a lot more metadata.

> and check it against MokListRT

Isn't this phase 2? I assume MokListRT is to check whether the kernel is signed with a valid key, to cope with the "_boot an old kernel on a machine with updated dbx_" issue?

> What's wrong with just having a "current" symlink

Would this be in /var/lib so it works with silverblue and atomic? It does all seem a bit magic.

> Do you think something analogous to e7bb68c is enough for the LiveCD check?

Ohh I didn't know about that; that seems sufficient to avoid running the service but I wonder if we want the same thing in the .c file too.

> I know this is a live image, do it anyway

Yes, agree.

**Comment by vathpela** [comment]
> > new dbx files will be broken down by EFI arch, so we have to decide how to handle that
> 
> I guessed per-EFI-arch subdirectories....

Works for me, though I'm not seeing how "x64/DBXUpdate.${irrelevant-but-visually-handy-date-code}.bin" is really better (or worse) than "DBXUpdate.x64.${irrelevant-but-visually-handy-date-code}.bin".  Both do seem slightly better than "DBXUpdate.${irrelevant-but-visually-handy-date-code}.x64.bin" because of the grouping in an alphabetized file listing.

> > stick it in the filename before or after the date code
> 
> I think encoding everything into the filename isn't going to work when we add even more metadata. I think at some point (now?) we need a catalog with a lot more metadata.

I don't want to add handling for complexity if we don't have a reason to believe there's complexity coming.  What more metadata are you thinking we will need beyond "which files contain lists I be trying to make sure all of are included on this system"?  What more do you think that question is a proxy for?

That said you've convinced me a current symlink won't work, simply because if the user is crazy enough to have two different KEKs issuing updates we can have more than one "current" file.  But if we did something like:
- everything we distribute goes in /usr/share/dbxtool (with arch subdir or arch filenames, whichever)
- local admins can also dump whatever they like in there
-  make (by default) /var/lib/dbxtool/01-uefi-ca.bin be a symlink to ../../../usr/share/dbxtool/${DB_FILE_WE_CHOSE}.bin
- Documenting that the behavior of the service and the default "dbxtool -a" and "dbxtool --check" behavior are all to load whatever is in /var/lib/dbxtool/
- Document that the sysadmin to copy or symlink in anything they need
- Document that nothing will automatically replace 01-uefi-ca.bin on an upgrade if it is either a regular file or a symlink to /dev/null (or whatever other criteria you may suggest)

As I see it we have the exact same complexity as before. What extra metadata are you thinking we're going to need?

> > and check it against MokListRT
> 
> Isn't this phase 2? I assume MokListRT is to check whether the kernel is signed with a valid key, to cope with the "_boot an old kernel on a machine with updated dbx_" issue?

I don't understand the question (phase 2 of what?) but I'll try to explain my thinking anyway.  MokListRT* include all of the keys and hashes from shim and MokList, so anything in it could potentially have been used to verify grub or kernel or both.  That could be because dbx has been updated, or because shim has been updated and no longer supports an old key, or because the machine owner builds and signs their own kernel, or any number of reasons.

> > What's wrong with just having a "current" symlink
> 
> Would this be in /var/lib so it works with silverblue and atomic? It does all seem a bit magic.

See above.
 
> > Do you think something analogous to [e7bb68c](https://github.com/rhboot/dbxtool/commit/e7bb68cb53bd08c34b7fe6f1ad6e15154f749eb9) is enough for the LiveCD check?
> 
> Ohh I didn't know about that; that seems sufficient to avoid running the service but I wonder if we want the same thing in the .c file too.

That's exactly what I meant to be asking ;)

**Comment by abazhaniuk** [comment]
Rather than assuming that we're detecting the ESP correctly, it would be good to check the contents of the BootOrder UEFI variables to confirm that we're checking the right shim when determining whether or not to do the dbx update.

Also, rather than just checking the timestamp of the certificate in the shim, since we have the contents of the dbx update which we'd like to apply to the system, we can calculate hashes for the shim and grub and determine directly if it will be blocked by the dbx update.  In the case of the two certificates that were revoked instead, we can use those revoked certificates to verify the signature of the shim and grub and if they pass, refuse to do the update until those are updated.
If the shim and grub don't match anything in the dbx update, we can still check the timestamp and warn about old certificates that we don't know anything about.

**Comment by hughsie** [comment]
> we can calculate hashes for the shim and grub and determine directly if it will be blocked by the dbx update

I'm literally just writing that code. :)

**Comment by vathpela** [comment]
Note that that's impossible to do reliably - for example, in the case where Boot#### has an abbreviated hard drive device path such as HD(1,GPT,927f5841-dc54-4ff4-821c-d29b59c48ab1,0x800,0x1ff800)/File(\EFI\fedora\shimx64.efi) , if you've got a md raid 1 with metadata format 0.99, so the RAID metadata is at the end of the disk, then both disks match this path, and which ever is probed first (or hopefully is being cached) is the ESP. The same is true of e.g. multipath devices without a specific multipath-aware EFI driver.

**Comment by hughsie** [comment]
> which ever is probed first (or hopefully is being cached) is the ESP

The fwupd code just mounts anything that looks like an ESP and just checks all the EFI binaries. I agree we can't really try to find the "correct ESP" as on my dual-boot system I have a windows 10 ESP and a different linux ESP on physically different disks.

**Comment by frozencemetery** [comment]
Thanks for your interest in dbxtool.  dbxtool has been obsoleted by [fwupd](https://github.com/fwupd/fwupd); we recommend using that instead and will shortly be archiving this repository.
